name: CI-CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run isready
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
